color_scheme: dark

plugins:
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-default-layout

url: https://docs.madelineproto.xyz
logo: logo.png

twitter:
  username: DaniilGentili
  card: summary
  
author:
  twitter: DaniilGentili
  
include: [".well-known"]
repository: danog/madelineproto
