theme: jekyll-theme-cayman
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-redirect-from

url: https://docs.madelineproto.xyz
logo: https://docs.madelineproto.xyz/logo.png

twitter:
  username: DaniilGentili
  card: summary
  
author:
  twitter: DaniilGentili
  
include: [".well-known"]

plugins:
  - jekyll-redirect-from
